# Use the latest version of docker compose
version: "3.2"
services:
    python:
      image: python:django
      container_name: c_python_django
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
      - type: bind
        source: ./
        target: /src/my_app
      ports:
      - "8000:8000"
